# Generated by Django 3.1.12 on 2025-05-11 00:17

import apps.veterinary_billing.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_mascota', models.CharField(max_length=50)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('productos', djongo.models.fields.ArrayField(blank=True, model_container=apps.veterinary_billing.models.ProductoEmbebido, null=True)),
                ('precio_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('precio_unitario', models.FloatField()),
            ],
        ),
    ]
