# Generated by Django 3.1.12 on 2025-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
    ]
