# Generated by Django 3.1.12 on 2025-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_inventory', '0002_auto_20250517_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='higiene',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='juguetes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
