# Generated by Django 3.1.12 on 2025-05-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_inventory', '0003_auto_20250517_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alimento',
        ),
        migrations.DeleteModel(
            name='Higiene',
        ),
        migrations.DeleteModel(
            name='Juguetes',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
