# Generated by Django 3.1.12 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_inventory', '0003_auto_20250331_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
