# Generated by Django 3.1.12 on 2025-03-31 00:44

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinary_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, default='Desconocida', max_length=50, null=True)),
                ('edad', models.IntegerField()),
                ('duenio', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('motivo_consulta', models.TextField()),
            ],
            options={
                'db_table': 'veterinary_clinic_historiaclinica',
                'managed': False,
            },
        ),
    ]
