# Generated by Django 5.1.2 on 2025-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=50)),
                ('edad', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
        ),
    ]
