# Generated by Django 3.1.12 on 2025-04-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_pets.especie')),
            ],
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
