# Generated by Django 3.1.12 on 2025-05-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0002_auto_20250410_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_pets.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pet', models.ManyToManyField(blank=True, to='veterinary_pets.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_pets.pet')),
            ],
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='nombre',
            new_name='specie',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_pets.especie'),
        ),
    ]
