# Generated by Django 3.1.12 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_pets', '0003_auto_20250509_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
